- hosts: sandy
  user: ubuntu
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: ping please
    local_action: command ping -c 4 172.31.83.220
  - name: install tree
    apt: pkg=tree state=latest
